# Generated by Django 6.0.2 on 2026-04-30 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action_type',
            field=models.CharField(choices=[('plan_change', 'Plan Changed'), ('trial_extend', 'Trial Extended'), ('payment_confirm', 'Payment Confirmed'), ('payment_reject', 'Payment Rejected'), ('payment_manual', 'Manual Payment Added'), ('user_login', 'Admin Login'), ('user_logout', 'Admin Logout'), ('user_export', 'User Data Exported'), ('payment_export', 'Payment Data Exported')], max_length=20),
        ),
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_plan_duration', models.CharField(choices=[('1', '1 Month'), ('3', '3 Months'), ('6', '6 Months'), ('12', '1 Year'), ('indefinite', 'Indefinite')], default='1', max_length=20)),
                ('default_trial_days', models.IntegerField(default=7, help_text='Default trial extension days')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications for admin actions')),
                ('dashboard_refresh_interval', models.IntegerField(default=5, help_text='Dashboard cache refresh interval in minutes')),
                ('auto_confirm_payments', models.BooleanField(default=False, help_text='Automatically confirm manual payments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Settings',
                'verbose_name_plural': 'Admin Settings',
            },
        ),
    ]
