# Generated by Django 6.0.2 on 2026-02-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_tags_loyaltyprogram_receipt_reminder_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='individual_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_promotions', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='segment',
            field=models.CharField(choices=[('all', 'All Customers'), ('loyal', 'Loyal Only'), ('regular', 'Regular'), ('new', 'New Customers'), ('atrisk', 'At-Risk'), ('individual', 'Individual Customer')], default='all', max_length=15),
        ),
    ]
