# Generated by Django 6.0.2 on 2026-04-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_tillpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan_paid_for',
            field=models.CharField(choices=[('free', 'Free Tier'), ('premium_retail', 'Retail Pro — KES 700/mo'), ('enterprise_ngo', 'Enterprise NGO — KES 3,500/mo'), ('enterprise_resort', 'Enterprise Resort — KES 3,500/mo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free Tier'), ('premium_retail', 'Retail Pro — KES 700/mo'), ('enterprise_ngo', 'Enterprise NGO — KES 3,500/mo'), ('enterprise_resort', 'Enterprise Resort — KES 3,500/mo')], default='free', max_length=20),
        ),
    ]
