# Generated by Django 6.0.2 on 2026-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment_invoice_number_alter_payment_plan_paid_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, default='', help_text='Safaricom CheckoutRequestID — used to match callbacks', max_length=100),
        ),
    ]
