import os
import sys
import subprocess

def run_cmd(cmd):
    print(f"🚀 Running: {cmd}")
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"❌ Error: {result.stderr}")
    else:
        print(f"✅ Success: {result.stdout}")
    return result.returncode

def main():
    print("🛠️ Starting Post-Repair Stabilization...")
    
    # 1. Ensure junction and system tables exist
    sql_commands = [
        # Admin log
        """CREATE TABLE IF NOT EXISTS "django_admin_log" (
            "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "action_time" timestamp with time zone NOT NULL,
            "object_id" text NULL,
            "object_repr" varchar(200) NOT NULL,
            "action_flag" smallint NOT NULL,
            "change_message" text NOT NULL,
            "content_type_id" integer NULL,
            "user_id" bigint NOT NULL
        )""",
        # Vendor groups (Permissions)
        """CREATE TABLE IF NOT EXISTS "vendors_vendor_groups" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "vendor_id" bigint NOT NULL,
            "group_id" integer NOT NULL,
            UNIQUE ("vendor_id", "group_id")
        )""",
        # Vendor user permissions
        """CREATE TABLE IF NOT EXISTS "vendors_vendor_user_permissions" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "vendor_id" bigint NOT NULL,
            "permission_id" integer NOT NULL,
            UNIQUE ("vendor_id", "permission_id")
        )""",
        # Session table
        """CREATE TABLE IF NOT EXISTS "django_session" (
            "session_key" varchar(40) NOT NULL PRIMARY KEY,
            "session_data" text NOT NULL,
            "expire_date" timestamp with time zone NOT NULL
        )""",
        # Add Foreign Keys if they don't exist (simplified)
        'CREATE INDEX IF NOT EXISTS "django_session_expire_date_a5c62663" ON "django_session" ("expire_date")',
        'CREATE INDEX IF NOT EXISTS "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id")',
        'CREATE INDEX IF NOT EXISTS "django_admin_log_user_id_c561a30a" ON "django_admin_log" ("user_id")'
    ]
    
    for cmd in sql_commands:
        # Wrap each in a management command to run raw SQL
        # Using a simple python string execution via manage.py shell
        print(f"Executing SQL: {cmd[:50]}...")
        subprocess.run(f'python manage.py shell -c "from django.db import connection; cursor = connection.cursor(); cursor.execute(\\"\\\"{cmd}\\"\\\" )"', shell=True)

    # 2. Fake the migration for vendors 0010 (the delete Sale migration)
    run_cmd("python manage.py migrate --fake vendors 0010")
    
    # 3. Fake all initial migrations so they are recorded as done
    run_cmd("python manage.py migrate --fake-initial")

    # 4. Final migration catch-all
    ret = run_cmd("python manage.py migrate")
    
    if ret == 0:
        print("🎉 Stabilization Complete!")
    else:
        print("⚠️ Migration finished with issues, but core fake was attempted.")
        sys.exit(ret)

if __name__ == "__main__":
    main()
