# Generated by Django 6.0.2 on 2026-04-22 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_email_businessnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
