# Generated by Django 6.0.2 on 2026-02-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(choices=[('food', 'Food Vendor'), ('printing', 'Printing / Cyber'), ('thrift', 'Thrift / Clothing'), ('rental', 'Rental Services'), ('cakes', 'Cakes & Confectionery'), ('general', 'General / Other')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='university',
            field=models.CharField(default='', max_length=120),
        ),
    ]
