# Generated by Django 6.0.2 on 2026-02-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_business_type_vendor_phone_vendor_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_type_custom',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(choices=[('food', 'Food Vendor'), ('printing', 'Printing / Cyber'), ('thrift', 'Thrift / Clothing'), ('rental', 'Rental Services'), ('cakes', 'Cakes & Confectionery'), ('general', 'General / Other'), ('other', 'Other (specify)')], default='general', max_length=30),
        ),
    ]
