# Generated by Django 6.0.2 on 2026-02-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_loginstreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
