# Generated by Django 6.0.2 on 2026-04-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_trial_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='mpesa_till_number',
            field=models.CharField(blank=True, default='', help_text='Used for C2B live payment tracking', max_length=20),
        ),
    ]
