# Generated by Django 6.0.2 on 2026-04-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendor_mpesa_till_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(choices=[('food', 'Food Vendor'), ('printing', 'Printing / Cyber'), ('thrift', 'Thrift / Clothing'), ('rental', 'Rental Services'), ('cakes', 'Cakes & Confectionery'), ('ngo', 'NGO / Non-Profit (Pro)'), ('resort', 'Resort / Hospitality (Pro)'), ('general', 'General / Other'), ('other', 'Other (specify)')], default='general', max_length=30),
        ),
    ]
