# Generated by Django 6.0.2 on 2026-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_vendor_business_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='university',
        ),
        migrations.AddField(
            model_name='vendor',
            name='brand_accent_color',
            field=models.CharField(default='#F59E0B', help_text='Hex color for your dashboard accents', max_length=7),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='Direct link to your business logo', max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='persona_type',
            field=models.CharField(choices=[('msme', 'Growth Hustler (MSME)'), ('ngo', 'Impact Maker (NGO)'), ('resort', 'Luxury Concierge (Resort)')], default='msme', max_length=20),
        ),
    ]
