# Generated by Django 6.0.2 on 2026-04-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_remove_vendor_university_vendor_brand_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='physical_address',
            field=models.TextField(blank=True, default='', help_text='Business physical location for tax/invoice compliance'),
        ),
    ]
