# Generated by Django 6.0.2 on 2026-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_vendor_physical_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='loyaltyreward',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(choices=[('food', 'Food Vendor'), ('printing', 'Printing / Cyber'), ('thrift', 'Thrift / Clothing'), ('rental', 'Rental Services'), ('cakes', 'Cakes & Confectionery'), ('ngo', 'NGO / Non-Profit (Pro)'), ('resort', 'Resort / Hospitality (Pro)'), ('other', 'Other')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='persona_type',
            field=models.CharField(choices=[('msme', 'Enterprise Builder (MSME)'), ('ngo', 'Impact Maker (NGO)'), ('resort', 'Luxury Concierge (Resort)')], default='msme', max_length=20),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='LoyaltyReward',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
