# Generated by Django 6.0.2 on 2026-04-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_remove_sale_customer_remove_loyaltyreward_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='has_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
