# Generated by Django 6.0.2 on 2026-04-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='resort_manager_pin',
            field=models.CharField(blank=True, help_text='4-digit PIN for sensitive manager analytics', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='resort_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='resort_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
