# Generated by Django 6.0.2 on 2026-04-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_vendor_resort_manager_pin_vendor_resort_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='kra_pin',
            field=models.CharField(blank=True, default='', help_text='KRA Personal Identification Number for Tax Compliance', max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='resort_manager_pin',
            field=models.CharField(blank=True, help_text='Hashed 4-digit PIN for sensitive manager analytics', max_length=128, null=True),
        ),
    ]
