# Generated by Django 6.0.2 on 2026-04-06 22:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_departments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(default=django.utils.timezone.now)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Checked-In (Open)'), ('closed', 'Checked-Out (Closed)'), ('canceled', 'Canceled')], default='open', max_length=20)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_folios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FolioCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='resort_portal.department')),
                ('folio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='resort_portal.folio')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_charges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResortGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('vip_status', models.BooleanField(default=False)),
                ('preferences', models.TextField(blank=True, help_text='e.g. Allergic to peanuts, prefers ground floor')),
                ('total_stays', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_guests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='folio',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='resort_portal.resortguest'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(default='Standard', max_length=100)),
                ('status', models.CharField(choices=[('vacant_clean', 'Vacant (Clean)'), ('vacant_dirty', 'Vacant (Needs Cleaning)'), ('occupied', 'Occupied'), ('maintenance', 'Out of Order')], default='vacant_clean', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('vendor', 'room_number')},
            },
        ),
        migrations.AddField(
            model_name='folio',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folios', to='resort_portal.room'),
        ),
    ]
