# Generated by Django 6.0.2 on 2026-04-08 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foliocharge',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_charges', to='resort_portal.resortguest'),
        ),
        migrations.AddField(
            model_name='resortguest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='resortguest',
            name='guest_type',
            field=models.CharField(choices=[('overnight', 'Overnight Guest'), ('day_visitor', 'Day Visitor (Picnic/Event/Dining)')], default='overnight', max_length=20),
        ),
        migrations.AddField(
            model_name='resortguest',
            name='nationality',
            field=models.CharField(blank=True, default='Kenyan', max_length=100),
        ),
        migrations.AddField(
            model_name='resortguest',
            name='passport_id',
            field=models.CharField(blank=True, help_text='ID or Passport Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='resortguest',
            name='preferences',
            field=models.TextField(blank=True, help_text='Flexible staff notes on guest preferences'),
        ),
    ]
