# Generated by Django 6.0.2 on 2026-04-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_portal', '0002_foliocharge_guest_resortguest_email_and_more'),
        ('vendors', '0012_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='resort_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='vendors.property'),
        ),
        migrations.AddField(
            model_name='folio',
            name='resort_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='vendors.property'),
        ),
        migrations.AddField(
            model_name='resortguest',
            name='resort_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='vendors.property'),
        ),
        migrations.AddField(
            model_name='room',
            name='resort_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='vendors.property'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('vacant_clean', 'Vacant (Clean)'), ('vacant_dirty', 'Vacant (Dirty)'), ('cleaning', 'Cleaning In Progress'), ('inspected', 'Ready for Inspection'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance / OOO')], default='vacant_clean', max_length=20),
        ),
        migrations.CreateModel(
            name='HousekeepingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(blank=True, max_length=100)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_logs', to='resort_portal.room')),
            ],
        ),
    ]
