# Generated by Django 5.x on 2026-04-16

from django.db import migrations

def populate_properties(apps, schema_editor):
    Vendor = apps.get_model('vendors', 'Vendor')
    Property = apps.get_model('vendors', 'Property')
    Room = apps.get_model('resort_portal', 'Room')
    Guest = apps.get_model('resort_portal', 'ResortGuest')
    Folio = apps.get_model('resort_portal', 'Folio')
    Department = apps.get_model('resort_portal', 'Department')

    for vendor in Vendor.objects.all():
        # Create default property
        prop, created = Property.objects.get_or_create(
            vendor=vendor,
            is_default=True,
            defaults={
                'name': f"{vendor.business_name} (Main)",
                'location': vendor.physical_address or "",
                'property_type': 'resort' if vendor.business_type == 'resort' else 'retail'
            }
        )
        # Update related models
        Room.objects.filter(vendor=vendor, resort_property__isnull=True).update(resort_property=prop)
        Guest.objects.filter(vendor=vendor, resort_property__isnull=True).update(resort_property=prop)
        Folio.objects.filter(vendor=vendor, resort_property__isnull=True).update(resort_property=prop)
        Department.objects.filter(vendor=vendor, resort_property__isnull=True).update(resort_property=prop)

class Migration(migrations.Migration):

    dependencies = [
        ('resort_portal', '0003_department_resort_property_folio_resort_property_and_more'),
        ('vendors', '0012_property'),
    ]

    operations = [
        migrations.RunPython(populate_properties),
    ]
