# Generated by Django 6.0.2 on 2026-04-16 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_portal', '0004_populate_properties'),
        ('vendors', '0012_property'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='department',
            name='resort_property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='vendors.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='folio',
            name='resort_property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='vendors.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resortguest',
            name='resort_property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='vendors.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='resort_property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='vendors.property'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('resort_property', 'room_number')},
        ),
    ]
