# Generated by Django 6.0.2 on 2026-04-16 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_portal', '0005_alter_room_unique_together_and_more'),
        ('vendors', '0012_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='foliocharge',
            name='resort_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='vendors.property'),
        ),
    ]
