# Generated by Django 6.0.2 on 2026-04-17 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_portal', '0006_foliocharge_resort_property'),
        ('vendors', '0013_vendor_resort_manager_pin_vendor_resort_otp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(default='Bar Stool', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('resort_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_seats', to='vendors.property')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_seats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DayPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('includes_services', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resort_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_passes', to='vendors.property')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_passes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DayVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('pass_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resort_portal.daypass')),
                ('resort_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_visitors', to='vendors.property')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_visitors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('space_type', models.CharField(max_length=50)),
                ('rate_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('resort_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_spaces', to='vendors.property')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_spaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organizer_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('resort_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bookings', to='vendors.property')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bookings', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='resort_portal.eventspace')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Open', max_length=50)),
                ('resort_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='vendors.property')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_facilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('table_type', models.CharField(default='Standard', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resort_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tables', to='vendors.property')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('icon', models.CharField(default='✨', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('guest', 'Guest Ops'), ('financial', 'Financial'), ('housekeeping', 'Housekeeping'), ('pos', 'Service/POS')], default='guest', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resort_property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='vendors.property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
