# Generated by Django 6.0.2 on 2026-04-17 15:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_portal', '0007_barseat_daypass_dayvisitor_eventspace_eventbooking_and_more'),
        ('vendors', '0013_vendor_resort_manager_pin_vendor_resort_otp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foliocharge',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='foliocharge',
            name='department',
        ),
        migrations.RemoveField(
            model_name='foliocharge',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='foliocharge',
            name='resort_property',
        ),
        migrations.RemoveField(
            model_name='foliocharge',
            name='vendor',
        ),
        migrations.CreateModel(
            name='StayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(default=django.utils.timezone.now)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Active'), ('closed', 'Completed'), ('canceled', 'Canceled')], default='open', max_length=20)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='resort_portal.resortguest')),
                ('resort_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='vendors.property')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stays', to='resort_portal.room')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_stays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer')], max_length=20, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='resort_portal.department')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_charges', to='resort_portal.resortguest')),
                ('resort_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='vendors.property')),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='resort_portal.barseat')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='resort_portal.restauranttable')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_charges', to=settings.AUTH_USER_MODEL)),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='resort_portal.stayrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='Folio',
        ),
        migrations.DeleteModel(
            name='FolioCharge',
        ),
    ]
