# Generated by Django 6.0.2 on 2026-04-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_portal', '0008_remove_foliocharge_folio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecharge',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount charged (VAT inclusive)', max_digits=10),
        ),
    ]
