# Generated by Django 6.0.2 on 2026-04-18 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_portal', '0009_servicecharge_net_amount_servicecharge_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stayrecord',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='resort_portal.resortguest'),
        ),
    ]
