# Generated by Django 6.0.2 on 2026-04-22 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_portal', '0013_manager_auth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerauth',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='managerauth',
            name='id',
        ),
        migrations.RemoveField(
            model_name='managerauth',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='managerauth',
            name='locked_until',
        ),
        migrations.RemoveField(
            model_name='managerauth',
            name='verification_expires',
        ),
        migrations.AddField(
            model_name='managerauth',
            name='failed_password_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='managerauth',
            name='failed_pin_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='managerauth',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerauth',
            name='last_pin_unlock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerauth',
            name='manager_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='managerauth',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='managerauth',
            name='password_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerauth',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerauth',
            name='pin_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerauth',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerauth',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managerauth',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='managerauth',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='managerauth',
            name='password_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='managerauth',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='managerauth',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manager_auth', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managerauth',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddIndex(
            model_name='managerauth',
            index=models.Index(fields=['email'], name='resort_port_email_dd975f_idx'),
        ),
        migrations.AddIndex(
            model_name='managerauth',
            index=models.Index(fields=['vendor'], name='resort_port_vendor__f00a19_idx'),
        ),
        migrations.AlterModelTable(
            name='managerauth',
            table='resort_portal_manager_auth',
        ),
    ]
