# Generated by Django 6.0.2 on 2026-04-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='email',
            field=models.EmailField(blank=True, help_text='For newsletters and program updates', max_length=254, null=True),
        ),
    ]
