# Generated by Django 6.0.2 on 2026-04-18 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_portal', '0002_beneficiary_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('significant_improvement', 'Significant Improvement'), ('stable', 'Stable / Progressing'), ('at_risk', 'At Risk / No Change'), ('declined', 'Declined / Regression')], default='stable', max_length=50)),
                ('is_goal_met', models.BooleanField(default=False, help_text='Did this intervention achieve the intended program outcome?')),
                ('narrative', models.TextField(blank=True, help_text='Detailed explanation of the change observed in the beneficiary.')),
                ('verified_at', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='ngo_portal.beneficiary')),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='ngo_portal.intervention')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_outcomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
